### ISSUE TITLE
Facebook link - content not availbale

### ISSUE THREAD

**Issue by Tamir198** [rohan-paul/Awesome-JavaScript-Interviews#24]
I have noticed that after clicking the Facebook link in the README:

![image](https://user-images.githubusercontent.com/34707669/187663652-8029d9dc-14ce-4205-af7c-a7005eefa1a6.png)

On the facebook site I  received content not available (the message is in Hebrew):

![image](https://user-images.githubusercontent.com/34707669/187663660-6b95e3a7-3d7c-4312-b193-4b72f682c2a6.png)

Is the facebook link relevant to the README?

**Comment by rohan-paul** [comment]
> I have noticed that after clicking the Facebook link in the README:
> 
> ![image](https://user-images.githubusercontent.com/34707669/187663652-8029d9dc-14ce-4205-af7c-a7005eefa1a6.png)
> 
> On the facebook site I received content not available (the message is in Hebrew):
> 
> ![image](https://user-images.githubusercontent.com/34707669/187663660-6b95e3a7-3d7c-4312-b193-4b72f682c2a6.png)
> 
> Is the facebook link relevant to the README?

Thanks for reporting @Tamir198 . Corrected.
